module.exports = {
  GUARD_USERNAME: process.env.GUARD_USERNAME,
  GUARD_PASSWORD: process.env.GUARD_PASSWORD,
  GUARD_TOKEN: process.env.GUARD_TOKEN,
  GUARD2_USERNAME: process.env.GUARD2_USERNAME,
  GUARD2_PASSWORD: process.env.GUARD2_PASSWORD,
  GUARD2_TOKEN: process.env.GUARD2_TOKEN,
  GUARD3_USERNAME: process.env.GUARD3_USERNAME,
  GUARD3_PASSWORD: process.env.GUARD3_PASSWORD,
  GUARD3_TOKEN: process.env.GUARD3_TOKEN
};
